botua = [
    r"check_ssl_cert.*",
    r"synthetic-monitoring-agent.*",
    r"monitoring360bot",
    r"WireReaderBot",
    r"monitoring360bot",
    r"Cloudflare-Healthchecks",
    r"(360Spider(?:-Image|-Video)?)",
    r"Aboundex",
    r"AcoonBot",
    r"AddThis\.com",
    r"AhrefsBot",
    r"AhrefsSiteAudit",
    r"ia_archiver|alexabot|verifybot",
    r"alexa site audit",
    r"Amazonbot-Video",
    r"Amazonbot",
    r"Amzn-SearchBot",
    r"Amzn-User",
    r"AmazonAdBot",
    r"NovaAct",
    r"AmazonBuyForMe",
    r"amazon-kendra",
    r"Amazon[ -]Route ?53[ -]Health[ -]Check[ -]Service",
    r"AmorankSpider",
    r"ApacheBench",
    r"Apache/",
    r"Applebot-Extended",
    r"Applebot",
    r"iTMS",
    r"AppSignalBot",
    r"Arachni",
    r"AspiegelBot",
    r"Castro 2, Episode Duration Lookup",
    r"Curious George",
    r"archive\.org_bot|special_archiver",
    r"Ask Jeeves/Teoma",
    r"Backlink-Check\.de",
    r"BacklinkCrawler",
    r"Baidu.*spider|baidu Transcoder",
    r"BazQux",
    r"Better Uptime Bot",
    r"MSNBot|msrbot|bingbot|bingadsbot|BingPreview|msnbot-(UDiscovery|NewsBlogs)|adidxbot",
    r"Blackbox Exporter",
    r"Blekkobot",
    r"BLEXBot",
    r"Bloglovin",
    r"Blogtrottr",
    r"BoardReader Blog Indexer",
    r"BountiiBot",
    r"Browsershots",
    r"BUbiNG",
    r"(?<!HTC)[ _]Butterfly/",
    r"CareerBot",
    r"CCBot",
    r"Cliqzbot",
    r"Cloudflare-AMP",
    r"Cloudflare-?Diagnostics",
    r"CloudFlare-AlwaysOnline",
    r"Cloudflare-SSLDetector",
    r"Cloudflare Custom Hostname Verification",
    r"Cloudflare-Traffic-Manager",
    r"Cloudflare-Smart-Transit",
    r"CloudflareObservatory",
    r"https://developers\.cloudflare\.com/security-center/",
    r"coccoc\.com",
    r"collectd",
    r"CommaFeed",
    r"CSS Certificate Spider",
    r"Datadog Agent|Datadog/?Synthetics",
    r"Datanyze",
    r"Dataprovider",
    r"Daum(?!(?:Apps|Device))",
    r"Dazoobot",
    r"discobot",
    r"Domain Re-Animator Bot|support@domainreanimator\.com",
    r"DotBot",
    r"DuckDuck(?:Go-Favicons-)?Bot",
    r"DuckAssistBot",
    r"EasouSpider",
    r"eCairn-Grabber",
    r"EMail Exractor",
    r"evc-batch",
    r"Exabot|ExaleadCloudview",
    r"ExactSeek Crawler",
    r"Ezooms",
    r"facebook(?:catalog|externalhit|externalua|platform|scraper)",
    r"meta-externalagent",
    r"meta-externalfetcher",
    r"meta-webindexer",
    r"meta-externalads",
    r"FacebookBot",
    r"Feedbin",
    r"FeedBurner",
    r"Feed Wrangler",
    r"Feedly",
    r"Feedspot",
    r"Fever/",
    r"FlipboardProxy|FlipboardRSS",
    r"Findxbot",
    r"FreshRSS",
    r"Genieo",
    r"GigablastOpenSource",
    r"Gluten Free Crawler",
    r"gobuster",
    r"ichiro",
    r"Storebot-Google",
    r"Google Favicon",
    r"Google Search Console",
    r"Google Page Speed Insights",
    r"google_partner_monitoring",
    r"Google-Cloud-Scheduler",
    r"Google-Structured-Data-Testing-Tool",
    r"GoogleStackdriverMonitoring",
    r"Google-Transparency-Report",
    r"Google-CloudVertexBot",
    r"Google-Firebase",
    r"Google-ilp",
    r"via ggpht\.com GoogleImageProxy",
    r"Google-Document-Conversion",
    r"GoogleDocs; apps-spreadsheets",
    r"GoogleDocs; apps-presentations",
    r"GoogleDocs;",
    r"SeznamEmailProxy",
    r"Seznam-Zbozi-robot",
    r"Heurekabot-Feed",
    r"ShopAlike",
    r"deepcrawl\.com",
    r"Googlebot-News",
    r"Google-Site-Verification",
    r"Google-Read-Aloud",
    r"Adwords-(?:DisplayAds|Express|Instant)|Google Web Preview|Google[ -]Publisher[ -]Plugin|Google-(?:adstxt|Ads-Conversions|Ads-Qualify|Adwords|AMPHTML|Assess|BusinessLinkVerification|HotelAdsVerifier|InspectionTool|Lens|PageRenderer|Shopping-Quality|Sites-Thumbnails|speakr|Stale-Content-Probe|Test|Youtube-Links)|(?:AdsBot|APIs|Feedfetcher|Mediapartners)-Google(?:-Mobile)?|Google(?:AdSenseInfeed|AssociationService|bot|Other|Prober|Producer|Sites)|Google.*/\+/web/snippet",
    r"Google-NotebookLM",
    r"Google-Extended",
    r"Gemini-Deep-Research",
    r"GoogleAgent-Mariner",
    r"GoogleAgent-Search",
    r"Bard-AI",
    r"Gemini-AI",
    r"Google-Pinpoint",
    r"^Google$",
    r"Google-Safety",
    r"DuplexWeb-Google",
    r"Google-Area120-PrivacyPolicyFetcher",
    r"HubSpot ",
    r"vuhuv(?:Bot|RBT)",
    r"HTTPMon",
    r"ICC-Crawler",
    r"inoreader\.com",
    r"iisbot",
    r"ips-agent",
    r"IP-Guide\.com",
    r"k6/",
    r"kouio",
    r"larbin",
    r"[A-z0-9]*-Lighthouse",
    r"last-modified\.com",
    r"linkdexbot|linkdex\.com",
    r"LinkedInBot",
    r"ltx71",
    r"Mail\.RU",
    r"magpie-crawler",
    r"MagpieRSS",
    r"masscan-ng",
    r".*masscan",
    r"Mastodon/",
    r"meanpathbot",
    r"MetaJobBot",
    r"MetaInspector",
    r"MixrankBot",
    r"MJ12bot",
    r"Mnogosearch",
    r"MojeekBot",
    r"munin",
    r"NalezenCzBot",
    r"check_http/v",
    r"nbertaupete95\(at\)gmail\.com",
    r"Netcraft(?: Web Server Survey| SSL Server Survey|SurveyAgent)",
    r"netEstate NE Crawler",
    r"Netvibes",
    r"NewsBlur .*(?:Fetcher|Finder)",
    r"NewsGatorOnline",
    r"nlcrawler",
    r"Nmap Scripting Engine",
    r"Nuzzel",
    r"NodePing",
    r"Octopus [\d.]+",
    r"OnlineOrNot\.com_bot",
    r"webzio-extended",
    r"webzio",
    r"omgili",
    r"OpenindexSpider",
    r"spbot",
    r"OpenWebSpider",
    r"OrangeBot|VoilaBot",
    r"PaperLiBot",
    r"phantomas/",
    r"phpservermon",
    r"Pocket(?:ImageCache|Parser)",
    r"PritTorrent",
    r"PRTG Network Monitor",
    r"psbot",
    r"Pingdom(?:\.com|TMS)",
    r"Quora Link Preview",
    r"Quora-Bot",
    r"RamblerMail",
    r"QuerySeekerSpider",
    r"Qwantify|Qwantbot",
    r"Rainmeter",
    r"redditbot",
    r"Riddler",
    r"rogerbot",
    r"ROI Hunter",
    r"SafeDNSBot",
    r"Scrapy",
    r"Screaming Frog SEO Spider",
    r"ScreenerBot",
    r"SemrushBot",
    r"BacklinksExtendedBot",
    r"SerpReputationManagementAgent",
    r"SplitSignalBot",
    r"SiteAuditBot",
    r"SensikaBot",
    r"SEOENG(?:World)?Bot",
    r"seoscanners\.net",
    r"SkypeUriPreview",
    r"SeznamBot|SklikBot|Seznam screenshot-generator",
    r"shopify-partner-homepage-scraper",
    r"ShopWiki",
    r"SilverReader",
    r"SimplePie",
    r"SISTRIX Crawler",
    r"compatible; (?:SISTRIX )?Optimizer",
    r"SiteSucker",
    r"sixy\.ch",
    r"Slackbot|Slack-ImgProxy",
    r"Sogou[ -](?:head|inst|Orion|Pic|Test|web)[ -]spider|New-Sogou-Spider",
    r"Sosospider|Sosoimagespider",
    r"Sprinklr",
    r"SSL Labs",
    r"StatusCake",
    r"Superfeedr bot",
    r"Sparkler",
    r"Spinn3r",
    r"SputnikBot",
    r"SputnikFaviconBot",
    r"SputnikImageBot",
    r"SurveyBot",
    r"TarmotGezgin",
    r"TelegramBot",
    r"TLSProbe",
    r"TinEye-bot",
    r"Tiny Tiny RSS",
    r"theoldreader\.com",
    r"Trackable/0\.1",
    r"trendictionbot",
    r"^Turnitin(?:Bot)?",
    r"TweetedTimes",
    r"TweetmemeBot",
    r"Twingly Recon",
    r"Twitterbot",
    r"UniversalFeedParser",
    r"via secureurl\.fwdcdn\.com",
    r"Uptime(?:bot)?/",
    r"UptimeRobot",
    r"URLAppendBot",
    r"Vagabondo",
    r"vkShare; ",
    r"VKRobot",
    r"VSMCrawler",
    r"Jigsaw",
    r"W3C_I18n-Checker",
    r"W3C-checklink",
    r"W3C_Validator|Validator\.nu",
    r"W3C-mobileOK",
    r"W3C_Unicorn",
    r"P3P Validator",
    r"Wappalyzer",
    r"PTST/",
    r"WeSEE",
    r"WebbCrawler",
    r"websitepulse[+ ]checker",
    r"WordPress.+isitwp\.com",
    r"Automattic Analytics Crawler",
    r"WordPress\.com mShots",
    r"wp\.com feedbot",
    r"WordPress",
    r"Wotbox",
    r"XenForo",
    r"yacybot",
    r"Yahoo! Slurp|Yahoo!-AdCrawler",
    r"Yahoo Link Preview|Yahoo:LinkExpander:Slingstone",
    r"YahooMailProxy",
    r"YahooCacheSystem",
    r"Y!J-(ASR|BR[IJOWY]|[BPW]SC)",
    r"Y!J",
    r"YandexBot.+MirrorDetector",
    r"(Yandex(?:(?:\.Gazeta |Accessibility|Com|Mobile|MobileScreenShot|RenderResources|Screenshot|Sprav)?Bot|(?:AdNet|Antivirus|Blogs|Calendar|Catalog|Dialogs|Direct(?:Dyn)?|Favicons|ForDomain|ImageResizer|Images|Market|Media(?:naBot)?|Metrika|News(?:links)?|OntoDB(?:API)?|Pagechecker|Partner|RCA|SearchShop|(?:News|Site)links|Tracker|Turbo|Userproxy|Verticals|Vertis|Video(?:Parser)?|Webmaster))|YaDirectFetcher)",
    r"YandexAdditional",
    r"Yeti|NaverJapan|AdsBot-Naver",
    r"YoudaoBot",
    r"YOURLS",
    r"YRSpider|YYSpider",
    r"zgrab",
    r"Zookabot",
    r"ZumBot",
    r"YottaaMonitor",
    r"Yahoo Ad monitoring.*yahoo-ad-monitoring-SLN24857",
    r".*Java.*outbrain",
    r"HubPages.*crawlingpolicy",
    r"Pinterest(?:bot)?/.*www\.pinterest\.com",
    r".*Site24x7",
    r".* HLB",
    r"s~snapchat-proxy",
    r"Snap URL Preview Service",
    r"SnapchatAds",
    r"GrapeshotCrawler",
    r"www\.monitor\.us",
    r"Catchpoint",
    r"bitlybot",
    r"Zao/",
    r"lycos",
    r"Slurp",
    r"Speedy ?Spider",
    r"nrsbot|NetResearchServer",
    r"scooter",
    r"gigabot",
    r"charlotte",
    r"Pompos",
    r"PagePeeker",
    r"WebThumbnail",
    r"Willow Internet Crawler",
    r"EmailWolf",
    r"NetLyzer FastProbe",
    r"AdMantX.*admantx\.com",
    r"Server Density Service Monitoring",
    r"RSSRadio \(Push Notification Scanner;support@dorada\.co\.uk\)",
    r"^sentry",
    r"^Spotify/[\d.]+$",
    r"Embedly",
    r"BrandVerity",
    r"Kaspersky Lab CFR link resolver",
    r"eZ Publish Link Validator",
    r"woorankreview",
    r"Siteimprove",
    r"CATExplorador",
    r"Buck",
    r"tracemyfile",
    r"zelist\.ro feed parser",
    r"weborama-fetcher",
    r"BoardReader Favicon Fetcher",
    r"IDG/(?:EU|IT|RU|UK)",
    r"Bytespider",
    r"TikTokSpider",
    r"WikiDo",
    r"Awario(?:Smart)?Bot",
    r"AwarioRssBot",
    r"oBot",
    r"SMTBot",
    r"LCC",
    r"Startpagina-Linkchecker",
    r"MoodleBot-Linkchecker",
    r"GTmetrix",
    r"CyberFind ?Crawler",
    r"Nutch",
    r"Seobility",
    r"Vercelbot",
    r"Grammarly",
    r"Domains Project",
    r"PetalBot",
    r"SerendeputyBot",
    r"ias-(?:va|sg).*admantx.*service-fetcher|admantx\.com.*service-fetcher",
    r"SemanticScholarBot",
    r"VelenPublicWebCrawler",
    r"Barkrowler",
    r"BDCbot",
    r"adbeat",
    r"(?:BuiltWith|BW/)",
    r"https://whatis\.contentkingapp\.com",
    r"MicroAdBot",
    r"PingAdmin\.Ru",
    r"notifyninja.+monitoring",
    r"WebDataStats",
    r"parse\.ly scraper",
    r"Nimbostratus-Bot",
    r"HeartRails_Capture",
    r"Project-Resonance",
    r"DataXu",
    r"Cocolyzebot",
    r"veryhip",
    r"LinkpadBot",
    r"MuscatFerret",
    r"PageThing\.com",
    r"ArchiveBox",
    r"Choosito",
    r"datagnionbot",
    r"WhatCMS",
    r"httpx",
    r".*\.oast\.",
    r"(?:expanseinc|paloaltonetworks)\.com",
    r"HuaweiWebCatBot",
    r"Hatena-Favicon",
    r"Hatena-?Bookmark",
    r"RyowlEngine",
    r"OdklBot",
    r"Mediatoolkitbot",
    r"ZoominfoBot",
    r"WeViKaBot",
    r"SEOkicks",
    r"Plukkie",
    r"proximic;",
    r"SurdotlyBot",
    r"Gowikibot",
    r"SabsimBot",
    r"LumtelBot",
    r"PiplBot",
    r"woobot",
    r"Cookiebot",
    r"NetSystemsResearch",
    r"CensysInspect",
    r"gdnplus\.com",
    r"WellKnownBot",
    r"Adsbot",
    r"MTRobot",
    r"serpstatbot",
    r"colly",
    r"l9tcpid",
    r"l9explore",
    r"l9scan/|^Lkx-.*/",
    r"MegaIndex\.ru",
    r"Seekport",
    r"Seolyt(?:Bot)?",
    r"YaK/",
    r"KomodiaBot",
    r"KStandBot",
    r"Neevabot",
    r"Chatwork LinkPreview",
    r"LinkPreview",
    r"JungleKeyThumbnail",
    r"rocketmonitor(?:bot)?",
    r"SitemapParser-VIPnytt",
    r"DMBrowser|DMBrowser-[UB]V",
    r"DataForSeoBot",
    r"Discordbot",
    r"Linespider",
    r"Cincraw",
    r"CISPA Web Analyzer",
    r"IonCrawl",
    r"Crawldad",
    r"https://securitytxt-scan\.cs\.hm\.edu/",
    r"TigerBot",
    r"TestCrawler",
    r"CrowdTanglebot",
    r"Sellers\.Guide Crawler by Primis",
    r"OnalyticaBot",
    r"deepnoc",
    r"Newslitbot",
    r"um-(?:ANS|CC|FC|IC|LN)",
    r"Abonti",
    r"collection@infegy\.com",
    r"HTTP Banner Detection \(https://security\.ipip\.net\)",
    r"ev-crawler",
    r"webprosbot",
    r"ELB-HealthChecker",
    r"Wheregoes\.com Redirect Checker",
    r"project_patchwatch",
    r"InternetMeasurement",
    r"DomainAppender",
    r"FreeWebMonitoring SiteChecker",
    r"Page Modified Pinger",
    r"adstxtlab\.com",
    r"Iframely",
    r"DomainStatsBot",
    r"aiHitBot",
    r"DomainCrawler/",
    r"AdAuth",
    r"faveeo\.com",
    r"kozmonavt\.",
    r"CriteoBot/",
    r"PayPal IPN",
    r"MaCoCu",
    r"CLASSLA",
    r"dnt-policy@eff\.org",
    r"InfoTigerBot",
    r"(?:Birdcrawlerbot|CrawlaDeBot)",
    r"ScamadviserExternalHit",
    r"ZaldamoSearchBot",
    r"AFB",
    r"LinkWalker",
    r"RenovateBot",
    r"INETDEX-BOT",
    r"NETZZAPPEN",
    r"panscient\.com",
    r"research@pdrlabs\.net",
    r"Nicecrawler",
    r"t3versionsBot",
    r"Crawlson",
    r"tchelebi",
    r"JobboerseBot",
    r"RepoLookoutBot",
    r"PATHspider",
    r"everyfeed-spider",
    r"Exchange check",
    r"Sublinq",
    r"Gregarius",
    r"COMODO DCV",
    r"Sectigo DCV|acme\.sectigo\.com",
    r"KlarnaBot-(?:DownloadProductImage|EnrichProducts|PriceWatcher)",
    r"Taboolabot",
    r"Asana",
    r"Chrome Privacy Preserving Prefetch Proxy",
    r"URLinspectorBot",
    r"EntferBot",
    r"TagInspector",
    r"pageburst",
    r"Doximity-Diffbot",
    r".+diffbot",
    r"DisqusAdstxtCrawler",
    r"startmebot",
    r"2ip bot",
    r"ReqBin Curl Client",
    r"XoviBot",
    r"Overcast/.+Podcast Sync",
    r"^Verity",
    r"hackermention",
    r"BitSightBot",
    r"Ezgif",
    r"intelx\.io_bot",
    r"FemtosearchBot",
    r"AdsTxtCrawler/",
    r"Morningscore",
    r"Uptime-Kuma",
    r"OAI-SearchBot",
    r"GPTBot",
    r"ChatGPT-User",
    r"ChatGPT-Browser",
    r"BrightEdge Crawler",
    r"sfFeedReader",
    r"cyberscan\.io",
    r"researchscan\.comsys\.rwth-aachen\.de",
    r"newspaper",
    r"Ant(?:\.com beta|Bot)",
    r"WebwikiBot",
    r"phpMyAdmin",
    r"Matomo/[\d.]+",
    r"Prometheus",
    r"ArchiveTeam ArchiveBot",
    r"MADBbot",
    r"MeltwaterNews",
    r"owler",
    r"bbc\.co\.uk/display/men/Page\+Monitor",
    r"BBC-Forge-URL-Monitor-Twisted",
    r"ClaudeBot|Anthropic-Claude",
    r"Claude-SearchBot",
    r"Claude-User",
    r"Claude-Web",
    r"Imagesift",
    r"TactiScout",
    r"Brightbot",
    r"DaspeedBot",
    r"StractBot",
    r"GeedoBot",
    r"GeedoProductSearch",
    r"BackupLand",
    r"Konturbot",
    r"keys-so-bot",
    r"LetsearchBot",
    r"Example3",
    r"StatOnlineRuBot",
    r"Spawning-AI",
    r"domain research project",
    r"getodin\.com",
    r"YouBot",
    r"SiteScoreBot",
    r"MBCrawler",
    r"mariadb-mysql-kbs-bot",
    r"GitHubCopilotChat",
    r"^pdrl\.fm",
    r"PodUptime/",
    r"anthropic-ai",
    r"NetpeakCheckerBot",
    r"SandobaCrawler",
    r"SirdataBot",
    r"CheckMarkNetwork",
    r"cohere-ai",
    r"Cohere-Command",
    r"cohere-training",
    r"PerplexityBot",
    r"Perplexity-User",
    r"TTD-Content",
    r"montastic-monitor",
    r"Ruby, Twurly v",
    r"Mixnode(?:Cache)?",
    r"CSSCheck",
    r"MicrosoftPreview",
    r"s~virustotalcloud",
    r"TinEye",
    r"e~arsnova-filter-system",
    r"botify",
    r"adscanner",
    r"online-webceo-bot",
    r"NetTrack",
    r"htmlyse",
    r"TrendsmapResolver",
    r"Shareaholic(?:bot)?",
    r"keycdn-tools:",
    r"keycdn-tools/",
    r"Arquivo-web-crawler",
    r"WhatsMyIP\.org",
    r"SenutoBot",
    r"GozleBot",
    r"Quantcastbot",
    r"FontRadar",
    r"ViberUrlDownloader",
    r"^Zeno$",
    r"Barracuda Sentinel",
    r"RuxitSynthetic",
    r"DynatraceSynthetic",
    r"sitebulb",
    r"Monsidobot",
    r"AccompanyBot",
    r"Ghost Inspector",
    r"Google-Apps-Script",
    r"SiteOne-Crawler",
    r"Detectify",
    r"DomCopBot",
    r"Paqlebot",
    r"Wibybot",
    r"Synapse",
    r"OSZKbot",
    r"ZoomBot",
    r"RavenCrawler",
    r"KadoBot",
    r"Dubbotbot",
    r"Swiftbot",
    r"EyeMonIT",
    r"ThousandEyes",
    r"OmtrBot",
    r"WebMoney Advisor",
    r"WebMon/",
    r"fragFINN",
    r"Clickagy",
    r"kiwitcms-gitops",
    r"webtru_crawler",
    r"URLSuMaBot",
    r"360JK yunjiankong",
    r"UCSBNetworkMeasurement",
    r"Plesk screenshot bot",
    r"Who\.is",
    r"Probely",
    r"Uptimia",
    r"2GDPR",
    r"abuse\.xmco\.fr",
    r"CheckHost",
    r"LAC_IAHarvester",
    r"InsytfulBot",
    r"statista\.com",
    r"SubstackContentFetch",
    r"^ds9",
    r"LiveJournal\.com",
    r"bitdiscovery",
    r"Castopod",
    r"Elastic/Synthetics",
    r"WDG_Validator",
    r"scan@aegis.network",
    r"CrawlyProjectCrawler",
    r"BDFetch",
    r"PunkMap",
    r"GenomeCrawlerd",
    r"Gaisbot",
    r"FAST-WebCrawler",
    r"ducks\.party",
    r"DepSpid",
    r"Website-info\.net",
    r"RedekenBot",
    r"semaltbot",
    r"MakeMerryBot",
    r"Timpibot",
    r"Validbot",
    r"NPBot",
    r"domaincodex\.com",
    r"Swisscows Favicons",
    r"leak\.info",
    r"workona",
    r"Bloglines",
    r"heritrix",
    r"search\.marginalia\.nu",
    r"vu-server-health-scanner",
    r"Functionize",
    r"Prerender",
    r"bl\.uk_ldfc_bot",
    r"Miniature\.io",
    r"Convertify",
    r"ZoteroTranslationServer",
    r"MuckRack",
    r"Golfe",
    r"SpiderLing",
    r"Bravebot",
    r"1001FirmsBot",
    r"SteamChatURLLookup",
    r"ohdear\.app",
    r"Inspici",
    r"peer39_crawler",
    r"Pandalytics",
    r"CloudServerMarketSpider",
    r"Pigafetta",
    r"Cotoyogi",
    r"SuggestBot",
    r"cms-experiment",
    r"SiteCheckerBotCrawler",
    r"SBIder",
    r"LightspeedSystemsCrawler",
    r"Research JLU",
    r"(?:hgf|OS)AlphaXCrawl",
    r"WPMU DEV",
    r"SnoopSecInspect",
    r"ModatScanner",
    r"researchcyber\.net",
    r"CrystalSemanticsBot",
    r"najdu\.s\.holubem\.eu",
    r"VORTEX/",
    r"xtate/(\d+\.[.\d]+)",
    r"FediList Agent/",
    r"Grafana/(\d+\.[.\d]+)",
    r"github-camo",
    r"Bluesky",
    r"OpenGraph\.io",
    r"microsoft-flow/",
    r"Simbiat Software",
    r"IbouBot",
    r"AddSearchBot",
    r"TerraCotta",
    r"KeybaseBot",
    r"Replicate-Bot",
    r"cypex\.ai",
    r"fhms-its-research-scanner",
    r"Together-Bot",
    r"xAI-Bot",
    r"Groq-Bot",
    r"bigsur\.ai",
    r"FirecrawlAgent",
    r"SecurityHeaders",
    r"HaloBot",
    r"RSiteAuditor",
    r"ORTc\.me",
    r"obsrvr\.net",
    r"AliyunSecBot",
    r"Mediumbot",
    r"Heexybot",
    r"ForwardQR",
    r"CybaaBot",
    r"CybaaAgent",
    r"DVbot",
    r"Assetnote",
    r"UGAResearchAgent",
    r"SERankingBacklinksBot",
    r"VertexWP",
    r"Friendica",
    r"Webliobot",
    r"sqalix",
    r"RecordedFuture",
    r"Valimail",
    r"FindFiles\.net",
    r"WanscannerBot",
    r"Kagibot",
    r"Ai2Bot-Dolma",
    r"Ai2Bot-DeepResearchEval",
    r"Ai2Bot",
    r"WARDBot",
    r"Character-AI",
    r"DeepseekBot",
    r"MistralAI-User",
    r"Crawlspace",
    r"Devin",
    r"Andibot",
    r"HypeStat",
    r"StatusNestBacklinkSpider",
    r"RunPod-Bot",
    r"HuggingFace-Bot",
    r"LinkBloom",
    r"img2dataset",
    r"iAskBot",
    r"LinerBot",
    r"Poggio-Citations",
    r"QualifiedBot",
    r"ZanistaBot",
    r"ChatGLM-Spider",
    r"gochitchat\.ai",
    r"SBIntuitionsBot",
    r"ias_crawler",
    r"ias_wombles",
    r"ShapBot",
    r"LumeWebScan",
    r"PanguBot",
    r"Manus-User",
    r"HubSpotContentSearchBot",
    r"ProRata",
    r"blackboardally",
    r"semantic-visions\.com",
    r"CopyvioDetector",
    r"Eyeotabot",
    r"YioopBot",
    r"yoozBot",
    r"(ABEvalBot|AdsTxtCrawlerTP|DNSResearchBot|Dormouse|FormFinder|GitCrawlerBot|HanaleiBot|ImportDomains|PrivacyPolicyBot|Robozilla|Secweb-Sectxt|SeoCherryBot|StudyBot|The Knowledge AI|Thinkbot|ThinkChaos|TprAdsTxtCrawler)",
    r"nuhk|grub-client|Download Demon|SearchExpress|Microsoft URL Control|borg|altavista|dataminr\.com|teoma|oegp|http%20client|htdig|mogimogi|larbin|scrubby|searchsight|semanticdiscovery|snappy|zeal(?!ot)|dataparksearch|findlinks|BrowserMob|URL2PNG|ZooShot|GomezA|Google SketchUp|Read%20Later|7Siters|centuryb\.o\.t9|InterNaetBoten|EasyBib AutoCite|Bidtellect|tomnomnom/meg|cortex|Re-re Studio|adreview|AHC/|NameOfAgent|Request-Promise|ALittle Client|Hello,? world|wp_is_mobile|0xAbyssalDoesntExist|Anarchy99|^revolt|nvd0rz|xfa1|Hakai|gbrmss|fuck-your-hp|IDBTE4M CODE87|Antoine|Insomania|Hells-Net|b3astmode|Linux Gnu \(cow\)|Test Certificate Info|iplabel|Magellan|TheSafex?Internetx?Search|Searcherx?web|kirkland-signature|LinkChain|survey-security-dot-txt|infrawatch|Time/|r00ts3c-owned-you|nvdorz|Root Slut|NiggaBalls|BotPoke|GlobalWebSearch|xx032_bo9vs83_2a|sslshed|geckotrail|Wordup|Keydrop|\(compatible\)|John Recon|SPARK COMMIT|masjesu|Komaru_The_Cat|Jesus Christ of Nazareth is LORD|Kowai|Hakai|LoliSec|LMAO|^xenu|^(?:chrome|desktop|firefox|Abcd|Dark|KvshClient|node|Node\.js|Report Runner|url|Zeus|ZmEu)$|OnlyScans|TheInternetSearchx|Laravel Reaver|bang2013|libredtail|Mozilliqa|Tiberius|honeygain|AW-WB-Filter|SaferSoftwashLeadGen|YourUserAgentHere|phpneuralnetwork",
    r"[a-z0-9_-]*(?:(?<!cu|Hu|power[ _]|m[ _])bot(?![ _]TAB|[ _]?5[0-9]|[ _]Senior|[ _]Junior)|analyzer|appengine|archiver?|checker|collector|crawl|crawler|(?<!node-|uclient-|Mikrotik/\d\.[x\d] |electron-)fetch(?:er)?|(?<!url)grabber|indexer|inspector|monitor|^parser|(?<!Microsoft |banshee-)project(?!or)|(?<!Google Wap |Blue |SpeedMode; )proxy|(?<!P)research|resolver|robots|(?<!Cam)scanner|scraper|script|searcher|(?<!-)security|spider(?! 8)|study|transcoder|uptime|user[ _]?agent|validator|-(?:AI|Extended|User)/)(?:[^a-z]|$)",
]
