[project]
name = "log-analysis"
version = "1.2.0"
description = ""
authors = [{ name = "Andrew Hankinson", email = "andrew.hankinson@gmail.com" }]
requires-python = ">=3.13,<4.0"
readme = "README.md"
dependencies = [
    "netaddr>=1.2.1,<2",
    "pyreqwest>=0.11.7,<0.12",
    "orjson>=3.11.3",
    "regex>=2025.11.3",
]

[dependency-groups]
dev = [
    "ipython>=9,<10",
    "mypy>=1.15.0",
    "pip>=25.0.1",
]

[tool.uv]
package = false

[build-system]
requires = ["hatchling", "pip"]
build-backend = "hatchling.build"

[tool.ruff]
target-version = "py313"

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # pycodestyle warnings
    "W",
    # Pyflakes
    "F",
    # pyupgrade
    ## Flake8 plugins
    "UP",
    # flake8-bugbear
    "B",
    # flake8-comprehensions
    "C",
    # flake8-django
    "DJ",
    # flake8-bandit
    "S",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]

ignore = [
    # Ignore Pycodestyle line-length warnings, (mainly long comments).
    "E501",
    # Ignore McCabe complexity (for now).
    "C901",
]
